[package]
name = "marki"
version = "0.1.0"
edition = "2024"

[lints.clippy]
pedantic = "warn"
perf = "warn"
nursery = "warn"

[dev-dependencies]
criterion = "0.5"
pulldown-cmark = "0.12"

[[bench]]
name = "parse"
harness = false

[[bench]]
name = "vs_pulldown_cmark"
harness = false

[profile.bench]
debug = true
